[profile.default]
src = "src"
out = "out"
libs = ["lib"]
libraries = ["src/library/EscrowLibrary.sol:EscrowUtils:0xFc84ceb72b62a7885124689e6ce615154CA04717"]
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
